//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Vinpearl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLY
    {
        public int maQL { get; set; }
        public string tenQL { get; set; }
        public string email { get; set; }
        public string matKhau { get; set; }
    }
}
